# Site settings
title: Industrial Data Analytics Lab
description: Industrial Data Analytics Lab
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Industrial Data Analytics Lab
user_description: 산업데이터 분석 연구실은 산업 현장의 데이터를 확보/분석을 통한 산학협력/컨설팅을 수행합니다. 
user_title:
email:
twitter_username:
github_username:
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
